### PR TITLE
#1-001 Build UI Templates for MyDiary App

### PR DESCRIPTION
**Pull request by dmithamo**
#### What does this PR do?
This PR submits the UI elements required by the _**MyDiary**_ app. It contains the pages needed for 
**User Sign Up**, **User Sign In**, **List of all Diary Entries** and **Detailed View of Each Entry**.

#### Description of Task to be completed
The PR adds UI elements, as required by **Challenge 1** of the **_MyDiary_** Challenge.

#### How should this be manually tested?
A preview of the UI elements is hosted on GitHub pages at [dmithamo/MyDiary](https://dmithamo.github.io/mydiary/) .

#### What are the relevant pivotal tracker stories?
This link leads to the relevant Pivotal Tracker stories [Pivotal Tracker - MyDiary](https://www.pivotaltracker.com/n/projects/2184320)
#### Screenshots
Homepage
image

Sign Up page
image

Sign In page
image

User Profile page
image

User Entries page
image

### CODE REVIEW

**Comment by ChegeBryan** [comment]
clean work... i love that place holder 'enter strong password'  😁

**Comment by dmithamo** [comment]
Hehe. Thanks man

**Comment by SrMoffat** [comment]
Good job man....I enjoy the dashboArd most

**Comment by dmithamo** [comment]
Thanks!

**Pull request merged**
