### PR TITLE
#001-2 : [Implement Feedback] Move Code to Develop Branch

### PR DESCRIPTION
**Pull request by dmithamo**
#### What does this PR do?
This PR is a response to the feedback/requirement that during development, code should be contained in the `develop` branch. It moves files previously merged to `master` (from the previous PR) off that branch to the `develop` branch. 
Further, all UI-related files are moved into one directory, in preparation for creating another directory to contain the API, for Challenge 2.
Only the `index.html` UI file is maintained in the root directory, to keep it accessible on GitHub Pages.

### CODE REVIEW

**Comment by inventiphGuru** [comment]
@dmithamo noting that you have merged the 4884b3d to develop
I thought you would first clean up then create the branch for the APi? or how have you done it?

**Comment by dmithamo** [comment]
I haven't started work on the API yet

**Comment by inventiphGuru** [comment]
ooh okay
then you will branch for the APi

**Comment by dmithamo** [comment]
Yes, yes. That's the plan

**Comment by inventiphGuru** [comment]
that is cool..

**Pull request merged**
