### PR TITLE
#159101428 Build out add_entry Endpoint

### PR DESCRIPTION
**Pull request by dmithamo**
#### What does this PR do?
The PR builds out the `POST mydiary/api/v1/entries`.

#### Description of Task to be completed?

`POST` request with `key : value` pairs for the required params can now be responded to by the API. 

#### How should this be manually tested?

Run the server as described in the [ReadMe](https://github.com/dmithamo/mydiary/blob/ft-api-add-entry-159101428/README.md) .

Use a tool like [Postman](https://www.getpostman.com/) or similar to test the API endpoint.
#### What are the relevant pivotal tracker stories?
[#159101428](https://www.pivotaltracker.com/story/show/159101428)

### CODE REVIEW

**Comment by caveinn** [comment]
Awesome.. However i would advice you to jsonify you responses

**Comment by dmithamo** [comment]
@caveinn 
My responses are `jsonify`-ed . For every response, the last thing I am doing before `return response` is `response = jsonify(result)` .

**Comment by charisschomba** [comment]
nice work bro ,but ensure you  intergrate with codacy for anlaysis of quality of your code.before merging

**Comment by caveinn** [comment]
Oh i hadn't noticed... Awesome work

**Comment by dmithamo** [comment]
Thank @charris.
Will look that up.
*Regards,*
*Dennis Mithamo.*

**Comment by dmithamo** [comment]
@charisschomba 
Thanks man.
I will look that up

**Comment by james-chege** [comment]
Nice work. If you happen to have any challenges hosting to heroku I'm here bro.

**Pull request merged**
